# Default initial positions for mi_robot_arm's ros2_control fake system

initial_positions:
  joint1: 0
  joint2: 0
  joint3: 0
  joint4: 0
  joint5: 0
  joint6: 0
  joint7: 0
  panda_finger_joint1: 0
  panda_finger_joint2: 0